### ISSUE TITLE
List all features that are in the examples but not yet in the specification [0.5D].

### ISSUE THREAD

**Issue by cmaumet** [Inria-Visages/BIDS-prov#10]
Delivrable: Itemized list in a markdown document in [current repository](https://github.com/Inria-Visages/BIDS-prov/).

**Comment by remiadon** [comment]
discussed with @cmaumet 
- Graphs on multiple files : useless, we always meant to define them on multiple files
- sha512 as @id, impossible because of different users using different hashing functions ...
- activities not present in the original set of examples
