### ISSUE TITLE
Updating description in BIDS-prov PR to BIDS-standard [1/2 day]

### ISSUE THREAD

**Issue by cmaumet** [Inria-Visages/BIDS-prov#11]
- In a google doc, write up a description that will go at the top of [PR to BIDS-standard](https://github.com/bids-standard/bids-specification/pull/439) including: listing all authors from the original google doc, giving a high-level description of what this PR is doing. 
 - Share with cmaumet and satra for feedback 
 - Post on the PR.

Deliverable : [PR to BIDS-standard](https://github.com/bids-standard/bids-specification/pull/439) with description updated.

**Comment by remiadon** [comment]
here : https://docs.google.com/document/d/1lVhhugGMT_DtwSsBMjzzjesjQISAIhdC69_zsEqbPdE/edit?usp=sharing

**Comment by remiadon** [comment]
@cmaumet  can you check out the first description in the doc ? Let me know if that's incomplete

**Comment by cmaumet** [comment]
Thank you @remiadon! I made a pass on the above document and added suggestions of edits. Can you have a look and accept the changes or let me know if you have further questions?

**Comment by cmaumet** [comment]
Note for myself: I need to ask satra about [the BEP guide](https://docs.google.com/document/d/1pWmEEY-1-WuwBPNy5tDAxVJYQ9Een4hZJM06tQZg8X4/edit?usp%3Dsharing&sa=D&ust=1537468908724000#heading=h.j0ubnow2d14u). In "When and how to start a BIDS Extension Proposal?" they recommend doing the discussions in the GDoc... I'd like to hear how other BEP have worked recently (since the move of BIDS-spec to GitHub).

**Comment by cmaumet** [comment]
@remiadon: Can you open your google doc to comment by anyone? I've pinged satra for feednback but currently the doc is not accessible to him. Thanks!
