### ISSUE TITLE
Add CodeOfConduct, Contributing guidelines, etc ... 

### ISSUE THREAD

**Issue by remiadon** [Inria-Visages/BIDS-prov#23]

**Comment by remiadon** [comment]
[READ THIS](https://docs.github.com/en/github/building-a-strong-community/setting-up-your-project-for-healthy-contributions)

* Code of conduct
* Contributing guidelines
* licence
* template for issues and PR

**Comment by cmaumet** [comment]
For code of conduct, we can probably use https://www.contributor-covenant.org/

**Comment by remiadon** [comment]
Template for issue OK
"Contributing guidelines"  -> see README
license OK
"Code of conduct" to be added ?

@cmaumet

**Comment by cmaumet** [comment]
Code of conduct, yes, see comment above I've proposed a link from which you can get the text.

**Comment by remiadon** [comment]
@cmaumet see 39a2610049d4fdbaed872c6d60f1eb4c44e23508

**Comment by remiadon** [comment]
Done, closing
