### ISSUE TITLE
Fork BIDS-specs and create a PR with the BIDS prov spec [1D]

### ISSUE THREAD

**Issue by cmaumet** [Inria-Visages/BIDS-prov#8]
- BIDS spec repo: https://github.com/bids-standard/bids-specification
 - [BIDS prov spec](https://docs.google.com/document/d/1vw3VNDof5cecv2PkFp7Lw_pNUTUo8-m8V4SIdtGJVKs/edit) inside  `03-modality-agnostic-files.md`

**Comment by remiadon** [comment]
see [here](https://github.com/bids-standard/bids-specification/pull/439)
